apiVersion: apps/v1
kind: Deployment
metadata:
  name: student_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student_backend
  template:
    metadata:
      labels:
        app: student_backend
    spec:
      containers:
      - name: student_backend
        image: shannan06/student_backend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: student_backend-service
spec:
  type: LoadBalancer
  selector:
    app: student_backend
  ports:
  - port: 80
    targetPort: 80