apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-portal
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
      - name: student-portal
        image: shannan06/student-portal:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: student-portal-service
spec:
  type: LoadBalancer
  selector:
    app: student-portal
  ports:
  - port: 80
    targetPort: 80